make scripts run from anywhere (#694)

diff --git a/deploy/terraform/bootstrap/sap_library/deployer_tfstate_script.tmpl b/deploy/terraform/bootstrap/sap_library/deployer_tfstate_script.tmpl
--- a/deploy/terraform/bootstrap/sap_library/deployer_tfstate_script.tmpl
+++ b/deploy/terraform/bootstrap/sap_library/deployer_tfstate_script.tmpl
@@ -1,21 +1,29 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+# exit immediately if a command fails
+set -o errexit
+
+# exit immediately if an unset variable is used
+set -o nounset
+
+readonly local_file_dir=$(dirname "$BASH_SOURCE")
 
 function main(){
 
     validate_deployer_tfstate
+    validate_deployer_remote_state
+    deployer_remote_backend_init
 }
 
 function validate_deployer_tfstate(){
 
-    echo "Check if terraform.tfstate of deployer exists:"
+    printf "%s\n" "Check if terraform.tfstate of deployer exists:"
 
     if [ ! -f "${deployer_terraform_tfstate_path}" ]; then
-        echo "${deployer_terraform_tfstate_path} does not exist."
+        printf "%s\n" "ERROR: ${deployer_terraform_tfstate_path} does not exist. Please follow guidance to create or recover it." >&2
         exit 2
     else 
-        echo "${deployer_terraform_tfstate_path} exists."
-        validate_deployer_remote_state
-        deployer_remote_backend_init
+        printf "%s\n" "INFO: ${deployer_terraform_tfstate_path} exists."
     fi
 }
 
@@ -24,22 +32,22 @@ function validate_deployer_remote_state(){
     az login --identity > /dev/null
     remote_state_exists=$(az storage blob exists -c ${storagecontainer_deployer_name} --name ${deployer_tfstate_name} --account-name ${tfstate_storage_account_name} | jq -r .exists)
     if $remote_state_exists; then
-        echo "remote state ${deployer_tfstate_name} already exists"
-        exit 0
+        printf "%s\n" "ERROR: remote state ${deployer_tfstate_name} already exists. It's only allowed to be pushed once." >&2
+        exit 1
     fi
 }
 
 function deployer_remote_backend_init(){
 
-    echo "Start initialize remote backend for deployer"
+    printf "%s\n" "Start initializing remote backend for deployer"
 
-    cp ${deployer_terraform_tfstate_path} ../
+    cd $${local_file_dir}/../
 
-    cd ..
+    cp ${deployer_terraform_tfstate_path} ./
 
-    echo "Clean .terraform if exists:"
+    printf "%s\n" "Clean local .terraform if exists:"
 
-    rm -r .terraform
+    rm -rf .terraform
 
     terraform init -force-copy \
     -backend-config "resource_group_name=${saplibrary_resource_group_name}" \
@@ -51,7 +59,5 @@ function deployer_remote_backend_init(){
 
     rm "${deployer_tfstate_name}"
 }
-
-
 
 main "$@"
diff --git a/deploy/terraform/bootstrap/sap_library/saplibrary_tfstate_script.tmpl b/deploy/terraform/bootstrap/sap_library/saplibrary_tfstate_script.tmpl
--- a/deploy/terraform/bootstrap/sap_library/saplibrary_tfstate_script.tmpl
+++ b/deploy/terraform/bootstrap/sap_library/saplibrary_tfstate_script.tmpl
@@ -1,21 +1,29 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+# exit immediately if a command fails
+set -o errexit
+
+# exit immediately if an unset variable is used
+set -o nounset
+
+readonly local_file_dir=$(dirname "$BASH_SOURCE")
 
 function main(){
 
     validate_saplibrary_tfstate
+    validate_saplibrary_remote_state
+    sap_library_remote_backend_init
 }
 
 function validate_saplibrary_tfstate(){
 
-    echo "Check if terraform.tfstate of sap library exists:"
+    printf "%s\n" "Check if terraform.tfstate of sap library exists:"
 
     if [ ! -f "${saplibrary_terraform_tfstate_path}" ]; then
-        echo "${saplibrary_terraform_tfstate_path} does not exist."
+        printf "%s\n" "ERROR: ${saplibrary_terraform_tfstate_path} does not exist. Please follow guidance to create or recover it." >&2
         exit 2
     else 
-        echo "${saplibrary_terraform_tfstate_path} exists."
-        validate_saplibrary_remote_state
-        sap_library_remote_backend_init
+        printf "%s\n" "INFO: ${saplibrary_terraform_tfstate_path} exists."
     fi
 }
 
@@ -24,22 +32,22 @@ function validate_saplibrary_remote_state(){
     az login --identity > /dev/null
     remote_state_exists=$(az storage blob exists -c ${storagecontainer_saplibrary_name} --name ${saplibrary_tfstate_name} --account-name ${tfstate_storage_account_name} | jq -r .exists)
     if $remote_state_exists; then
-        echo "remote state ${saplibrary_tfstate_name} already exists"
-        exit 0
+        printf "%s\n" "ERROR: remote state ${saplibrary_tfstate_name} already exists. It's only allowed to be pushed once." >&2
+        exit 1
     fi
 }
 
 function sap_library_remote_backend_init(){
 
-    echo "Start initialize remote backend for sap library"
+    printf "%s\n" "Start initializing remote backend for sap library"
 
-    cp ${saplibrary_terraform_tfstate_path} ../
+    cd $${local_file_dir}/../
 
-    cd ..
+    cp ${saplibrary_terraform_tfstate_path} ./
     
-    echo "Clean .terraform if exists:"
+    printf "%s\n" "Clean local .terraform if exists:"
     
-    rm -r .terraform
+    rm -rf .terraform
 
     terraform init -force-copy \
     -backend-config "resource_group_name=${saplibrary_resource_group_name}" \
@@ -49,7 +57,7 @@ function sap_library_remote_backend_init(){
 
     terraform state push "${saplibrary_tfstate_name}"
 
-    terraform state rm 'local_file.sa_config' 'local_file.output_saplibrary_script' 'local_file.output_deployer_script' 'null_resource.copy_input'
+    terraform state rm 'local_file.sa_config' 'local_file.output_saplibrary_script' 'local_file.output_deployer_script'
 
     rm "${saplibrary_tfstate_name}"
 }
